name: Build + Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: mozilla-actions/sccache-action@v0.0.6
      - id: version
        uses: dante-signal31/rust-app-version@v1.2.0
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo build --release
      - run: ls $HOME/work/wordhooks-rs/wordhooks-rs/target/release/
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/bn0367/wordhooks-rs:${{ steps.version.outputs.app_version}}b${{github.run_number}},ghcr.io/bn0367/wordhooks-rs:latest
          platforms: linux/arm64
          context: .